Clever/http-science

main.go

I don't think this is the reason we stop logging diffs, but I figure we should
fix it either way.

Record error with write proxy

---

.drone.yml
Dockerfile
Godeps/Godeps.json
Godeps/Readme
Makefile
README.md
main_test.go

This PR was mostly autogenerated.
Changes to expect:
- removal of `*_test.go` files in /vendor
- addition of non go files in /vendor
- addtions to README.md & Makefile
**Before your merge!**:
- Please carefully check the Makefile changes
- Ensure that the build is passing
- Check that drone is using the proper image (Clever/drone-go:1.5)
Feel free to ping @natebrennand or #golang for clarification or help.
If you'd like more of an explanation please join us in #golang.

Go Vendoring Standardization

---

main.go

Remove the Transfer-Encoding and Content-Length headers. We've seen
some false positives where the control returns one and the experiment
returns the other, but they return the same body. Since we're
already checking the body and the way the data is sent over HTTP doesn't
matter, let's ignore these.

Ignore transfer-encoding and content-length headers

---

email/email.go

We were previously getting `Status:"rejected", RejectionReason:"invalid-sender"` because I hadn't configured the new mandrill template correctly (didn't specify a from address). I have changed that and this should check for similar errors in future.

Add check that email was sent

---

.drone.yml

Context:  https://clever.atlassian.net/browse/INFRA-1577
Refactor so that report-card is invoked via a Publish block;
this lets Drone do the heavy-lifting instead of setting it up locally.
Expected changes:
- ADDED
- A single entry in the "publish" block `report_card: {}` (if this wasn't already present)
- REMOVED
- All "env" block entries related to report-card are removed
- All "script" block entries related to report-card are removed
- MODIFIED
- YAML reformatting/linting (side-effect)
**Please verify by looking at the build logs**
1. Your build ran successfully (all tests and script steps completed)
2. Report card ran successfully (you can see it in the
If you see any errors in the above, please loop @nathanleiby (@n on Slack) into the PR.
Thanks!

Simpler report-card invocation: http-science

---

.drone.yml
config/config.go
main.go
science/common.go
science/common_test.go
science/compare.go
science/compare_test.go
science/correctness.go
science/correctness_test.go
science/load.go
science/load_test.go
validate/validate.go

This adds the option to do json diffing. We try a simple string match between the bodies and if that fails we try to do a json comparison.
In the json comparison, we ignore differences in the order of keys (correct according to the json spec), and add the option (by default OFF) to ignore ordering in arrays (incorrect according to the json spec). However we need to do this second part as in some places we use go maps.
These is a bit of refactoring to allow us to do this.
Fairly extensive tests of the comparisons have been added.
I'll run some sanity tests in dev to test this too.

Json compare

---

getfiles/getfiles.go

`Read()` makes no guarantee that the number of returned bytes is equal to
the number of requested bytes, so this was almost always exiting the
loop early. For example, the file I tested with only listed 60 requests
before this commit even though there were actually 1940 requests in the
file.

getfiles: Actually decompress the entire file.

---

science/correctness.go

I'm not 100% sure what is happening, but I think that with weak_equal, comparisons of very large docs takes a very long time (it is an n^2 process). While doing that comparison, nothing else can make progress as we lock during the check. That is unnecessary - there is no concurrent access to anything in the checks.
Todo is maybe to try make weak equal more performant, but this should alleviate it a bit.

only lock where we really need to

---

getfiles/getfiles.go

We were getting nil pointer dereference errors because `defer reader.Close()` was being called before checking that there are no errors.
```
Thu 19:29:56.844 http-science/cff26bae~> panic: runtime error: invalid memory address or nil pointer dereference
Thu 19:29:56.844 http-science/cff26bae~> [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x5b0a92]
Thu 19:29:56.844 http-science/cff26bae~> goroutine 6 [running]:
Thu 19:29:56.844 http-science/cff26bae~> panic(0x6fcfa0, 0xc420016060)
Thu 19:29:56.844 http-science/cff26bae~> #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Thu 19:29:56.844 http-science/cff26bae~> compress/gzip.(*Reader).Close(0x0, 0x8adde0, 0xc420016840)
Thu 19:29:56.844 http-science/cff26bae~> #011/usr/local/go/src/compress/gzip/gunzip.go:287 +0x22
Thu …
```

Close readers after error checking

---

config/config.go
gor/run_gor.go

It's like https://github.com/Clever/http-science/pull/36 but the opposite. Useful if you have a rarely hit endpoint

only run with specified urls

---

config/config.go
science/correctness.go
validate/validate.go

Add a concurrency option rather than speed for correctness tests.
Speed is hard to use.

Concurrent rate limit

---

science/correctness.go

I believe this can cause the server to return 304s, making the response
harder to debug.

Remove If-None-Match header

---

circle.yml

*Risk rating*: 1 clever clover :four_leaf_clover:  
*or* 0.1 oauth deploys :shipit:
So free to merge yourself
After much discussion, it seems worthwhile to enable docker builds on all branches.  It's always been difficult to deploy development branches to dev.  Which is kinda ironic.  Don't you think? It's like ten thousands tests when all you need is a deploy.  It's like breaking the build by merging to master.  Isn't it ironic?  It's a little too ironic.  I really do think.
Once merged, you'll be able to run `ark start Clever/http-science -b <branch>` on a whim.  No more "temporary" changes to [circle.yml](https://github.com/Clever/app-view-service/commit/dbcf816fd208ac42b2821b831b0297978dc6526c#diff-29944324a3cbf9f4bd0162dfe3975d88).  After this PR, you'll live in a world free of …

Enabling docker builds on all branches for Clever/http-science

---

launch/http-science.yml

*Risk rating*: :moneybag::moneybag::money_with_wings:
Worst case scenario, jobs are a bit slower and fail slightly more often.  The vast majority of our cluster's CPU is unutilized, so it's unlikely the worst case scenario will happen.
By their nature, workers are asynchronous, which means most of the time they're not doing much and when they are doing something, it's not super important that they do it quickly.
***But with 0 CPU, how will my worker compute anything?***
Our cluster has CPU for dayz.  Your container will probably run on a machine with an underutilized CPU, which means if your container needs more CPU, it'll get CPU.  That's why it's okay to set a container's CPU to 0.  You can think of the [CPU value](https://github.com/Clever/catapult/blob/65acdd4214a9a878aaf4369670d508cfe …

Lowered http-science's cpu allocation to 0

---

Dockerfile
Makefile
golang.mk
launch/http-science.yml
sfncli.mk

*Risk rating*: Major :skull:  **Don't merge.**  Just Review.
If this worker relies on T_T or on JOB_ID for more than logging, holler.  If this worker talks directly to gearman, scream.  That's really not good.
Infra will schedule time to roll this migration out in production.
We're killing gearman, which means by proxy we're killing gearcmd.  Workers must now use sfncli.  This PR migrates workers to sfncli.
**New constraints**:
- Workers must take JSON as input
- Workers must use `stderr` for logging.  Only results can go to `stdout`.
- Workers must use [Catapult roles](https://clever.atlassian.net/wiki/spaces/ENG/pages/106506447/AWS+Identity+IAM+STS+Roles#AWSIdentity(IAM,STS,Roles)-CatapultIAMroles(awsinlaunch.yml))
Also gearman-admin is going a way.  Hubble is the new hawtness: …

Migrating http-science's to sfncli

---

README.md
config/config.go
getfiles/getfiles.go
validate/validate.go

Change payload to take in `ServiceName` and envs flags. This way we only need to specify the service name once in the payload and we can infer all of the other information from it
old sample payload:
```
{
"concurrency": 10,
"control_url": "https://clever-dev--events-api.int.clever.com:443",
"diff_loc": "s3://replay-testing/john_events-api_2019-03-28.txt",
"email": "john.huang@clever.com",
"experiment_url": "https://john--events-api.int.clever.com:443",
"file_prefix": "replay-testing/events-api",
"job_type": "correctness",
"reqs": 50000,
"s3_bucket": "firehose-prod"
}
```
new sample payload:
```
{
"concurrency": 10,
"service_name": "events-api",
"control_env": "clever-dev",
"experiment_env": "john",
"diff_loc": "s3://replay-testing/john_events-api_2019-03-28.txt",
"email": …
```

ServiceName field to determine other config fields

---

config/config.go
validate/validate.go

With some services being moved to pods, it would be useful to specify an optional `podID` param. Without the pod ID, I am seeing a forwarding error (e.g `error establishing tcp connection to ilel-exp--sso-cil-event-logs-service.int.clever.com:443: dial tcp: lookup ilel-exp--sso-cil-event-logs-service.int.clever.com on 10.0.0.2:53: no such host`)

Add optional pod id field to payload

---

.circleci/config.yml

The default as of writing is 20.10.17, which is higher than this pinned version.

Unpin CircleCI Docker version

---

launch/http-science.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5056
**Overview:**
In this PR we will migrate all workers in this repo to use app mesh. We are migrating this worker to mesh_only state directly instead of hybrid as workers don't have albs and hybrid state is not valid for them.
After this PR is merged the workers will start running with a envoy proxy sidecar which will handle all the networking. As applications haven't been migrated to the mesh yet, this change should not cause a significant difference.
**Rollout:**
- Workers have no upstreams so nothing to do here other than merge PR and monitor dapple deploy
- monitor cpu and memory

migrate workers to app mesh in mesh_only state in dev

---

launch/http-science.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5056
**Overview:**
In this PR we will migrate all workers in this repo to use app mesh. We are migrating this worker to mesh_only state directly instead of hybrid as workers don't have albs and hybrid state is not valid for them.
After this PR is merged the workers will start running with a envoy proxy sidecar which will handle all the networking. As applications haven't been migrated to the mesh yet, this change should not cause a significant difference.
**Rollout:**
- Workers have no upstreams so nothing to do here other than merge PR and monitor dapple deploy
- monitor cpu and memory

migrate workers to app mesh in mesh_only state in prod

---

launch/http-science.yml

**Jira:** https://clever.atlassian.net/browse/INFRANG-5936
This PR migrates the app to us-west-2
Dev:
1. Deploy in us-west-2 clever-dev or dev-infra environment (merging not mandatory)
2. Restart upstream services
3. Team owners to test if dev service is functional in us-west-2
4. Kill the older deployment in us-west-1 after confirming successful deploy and traffic flow/activity
Prod:
1. Get approval from app owners
2. Deploy in us-west-2 after merging
3. Restart upstream services
4. Traffic to pods can be verified in Grafana
5. Kill the older prod deployment in us-west-1 after a minimum of 3 days only after confirming all traffic is coming thru to the new deployment

change pod group to uw2

---

launch/http-science.yml

https://clever.atlassian.net/browse/INFRANG-6012
Delete the mesh config as we are exiting mesh and this mesh_config is not used anymore.
Currently catapult is using a feature flag in place of this mesh config and the feature flag is set to "alb_only" for this app. Which means this is already running in production
Merge PR and deploy via dapple

remove mesh_config

---

.circleci/config.yml
Dockerfile
go.mod
golang.mk
sfncli.mk

**Jira:**
https://clever.atlassian.net/browse/INFRANG-5737
**Overview:**
This is a combination of the go 1.21 upgrade, + sfncli and docker changes needed to avoid the glibc issue. This had to be rebased on master to avoid go.mod changes being overwritten and downgrading imports accidentally. 
We are asking the teams to review **AND TEST**  these PRs in clever-dev as they have greater context on what those tests should look like. 
NOTE: Since our local/ci testing do not use the same docker images as production all testing should be done by actually deploying this modified version. 
If there are any problems and you need help feel free to reach out via slack in #go121-update 
When you are finished testing please edit this PR description to add testing notes so that it passes SOC2 validation …

update to go1.21
